# Generated by Django 6.0.4 on 2026-06-02 07:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(default='Контакты', max_length=255, verbose_name='Заголовок')),
                ('city', models.CharField(default='Тюмень', max_length=100, verbose_name='Город')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('map_embed_url', models.URLField(blank=True, help_text='Например src из iframe Яндекс.Карт', verbose_name='Ссылка iframe-карты')),
                ('social_links', wagtail.fields.StreamField([('social', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Название'}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('url', 1), ('icon', 2)]], {'label': 'Соцсеть'})}, verbose_name='Соцсети')),
                ('content', wagtail.fields.StreamField([('rich_text', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}, verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
            bases=('wagtailcore.page',),
        ),
    ]
