# Generated by Django 6.0.4 on 2026-06-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyPolicyPage',
            new_name='LegalDocumentPage',
        ),
        migrations.AlterModelOptions(
            name='legaldocumentpage',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
