# Generated by Django 6.0.4 on 2026-06-29 07:59

import base.page_blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0002_rename_privacypolicypage_legaldocumentpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocumentpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("text_section", base.page_blocks.RichTextSectionBlock()),
                    ("table", base.page_blocks.TableSectionBlock()),
                ],
                blank=True,
                verbose_name="Содержимое страницы",
            ),
        ),
    ]
