# Generated by Django 6.0.4 on 2026-05-19 06:34

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(default='Кейсы', max_length=255, verbose_name='Заголовок')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Кейсов на странице')),
            ],
            options={
                'verbose_name': 'Лента кейсов',
                'verbose_name_plural': 'Ленты кейсов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SingleCasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Название компании-клиента')),
                ('industry', models.CharField(choices=[('oil-gas', 'Нефтегаз'), ('service_business', 'Сервисный бизнес'), ('trading', 'Торговля'), ('production', 'Производство')], max_length=100, verbose_name='Отрасль')),
                ('project_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата реализации проекта')),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Длительность проекта')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='1-3 предложения для анонса', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('text_section', 2), ('metrics', 8), ('results', 13), ('technologies', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Ключевые показатели', 'label': 'Заголовок блока', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Значение', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Описание', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('value', 4), ('label', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Метрики'}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('items', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты', 'label': 'Заголовок блока', 'required': False}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст результата', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('text', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Список результатов'}), 13: ('wagtail.blocks.StructBlock', [[('title', 9), ('items', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Технологии', 'label': 'Заголовок блока', 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Список технологий'}), 17: ('wagtail.blocks.StructBlock', [[('title', 14), ('items', 16)]], {})}, verbose_name='Содержание кейса')),
                ('customer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип клиента')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
            bases=('wagtailcore.page',),
        ),
    ]
