# Generated by Django 6.0.4 on 2026-06-23 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlecasepage',
            name='content',
            field=wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('features', 11), ('results', 16), ('technologies', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Описание', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список пунктов'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты', 'label': 'Заголовок блока', 'required': False}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст результата', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('text', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Список результатов'}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('items', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Технологии', 'label': 'Заголовок блока', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Список технологий'}), 20: ('wagtail.blocks.StructBlock', [[('title', 17), ('items', 19)]], {})}, verbose_name='Содержание кейса'),
        ),
    ]
