# Generated by Django 6.0.4 on 2026-06-24 09:14

import django.db.models.deletion
from django.db import migrations, models


LEGACY_INDUSTRIES = [
    ("oil-gas", "Нефтегаз", 10),
    ("service_business", "Сервисный бизнес", 20),
    ("trading", "Торговля", 30),
    ("production", "Производство", 40),
]


def migrate_industries_forward(apps, schema_editor):
    CaseIndustry = apps.get_model("cases", "CaseIndustry")
    SingleCasePage = apps.get_model("cases", "SingleCasePage")

    industries_by_value = {}
    for value, name, order in LEGACY_INDUSTRIES:
        industry, _ = CaseIndustry.objects.get_or_create(
            value=value,
            defaults={
                "name": name,
                "order": order,
            },
        )
        industries_by_value[value] = industry

    for case in SingleCasePage.objects.exclude(industry__isnull=True).exclude(industry=""):
        industry = industries_by_value.get(case.industry)
        if industry:
            case.industry_new_id = industry.id
            case.save(update_fields=["industry_new"])


def migrate_industries_backward(apps, schema_editor):
    SingleCasePage = apps.get_model("cases", "SingleCasePage")

    for case in SingleCasePage.objects.select_related("industry_new").filter(
        industry_new__isnull=False
    ):
        case.industry = case.industry_new.value
        case.save(update_fields=["industry"])


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_singlecasepage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseIndustry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "value",
                    models.SlugField(
                        max_length=100,
                        unique=True,
                        verbose_name="Значение для URL",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Отрасль кейса",
                "verbose_name_plural": "Отрасли кейса",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="singlecasepage",
            name="industry_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cases.caseindustry",
                verbose_name="Отрасль",
            ),
        ),
        migrations.RunPython(
            migrate_industries_forward,
            migrate_industries_backward,
        ),
        migrations.RemoveField(
            model_name="singlecasepage",
            name="industry",
        ),
        migrations.RenameField(
            model_name="singlecasepage",
            old_name="industry_new",
            new_name="industry",
        ),
        migrations.AlterField(
            model_name="singlecasepage",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="cases.caseindustry",
                verbose_name="Отрасль",
            ),
        ),
    ]
