# Generated by Django 6.0.4 on 2026-07-08 07:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseindustry_alter_singlecasepage_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlecasepage',
            name='content',
            field=wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('features', 11), ('results', 16), ('technologies', 20), ('rates', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Описание', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список пунктов'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Результаты', 'label': 'Заголовок блока', 'required': False}), 13: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Текст результата', 'required': True}), 14: ('wagtail.blocks.StructBlock', [[('text', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Список результатов'}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('items', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Технологии', 'label': 'Заголовок блока', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Технология'}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Список технологий'}), 20: ('wagtail.blocks.StructBlock', [[('title', 17), ('items', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'label': 'Период тарифа', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Цена продления', 'label': 'Заголовок цены', 'required': False}), 23: ('wagtail.blocks.CharBlock', (), {'label': 'Цена тарифа', 'required': True}), 24: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 25: ('wagtail.blocks.CharBlock', (), {'default': '#contacts', 'help_text': 'Например: #contacts, /contacts/, https://example.com', 'label': 'Ссылка или якорь', 'max_length': 255, 'required': True}), 26: ('wagtail.blocks.StructBlock', [[('text', 24), ('url', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Рекомендованная цена', 'label': 'Заголовок рекомендованной цены', 'required': False}), 28: ('wagtail.blocks.TextBlock', (), {'label': 'Рекомендованная цена', 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('title', 6), ('period', 21), ('price_title', 22), ('price', 23), ('button', 26), ('rec_price_title', 27), ('rec_price', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'label': 'Список тарифов'}), 31: ('wagtail.blocks.StructBlock', [[('title', 0), ('rates', 30)]], {})}, verbose_name='Содержание кейса'),
        ),
    ]
