# Generated by Django 6.0.4 on 2026-09-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_singlecasepage_content'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlecasepage',
            old_name='customer_logo',
            new_name='card_image',
        ),
        migrations.AddField(
            model_name='singlecasepage',
            name='after_text',
            field=models.TextField(blank=True, verbose_name='Стало'),
        ),
        migrations.AddField(
            model_name='singlecasepage',
            name='before_text',
            field=models.TextField(blank=True, verbose_name='Было'),
        ),
        migrations.AlterField(
            model_name='singlecasepage',
            name='card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение карточки'),
        ),
        migrations.AddField(
            model_name='singlecasepage',
            name='work_text',
            field=models.TextField(blank=True, verbose_name='Сделали'),
        ),
    ]
