# Generated by Django 6.0.4 on 2026-05-19 05:00

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(default='Услуги', max_length=255, verbose_name='Заголовок')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Услуг на странице')),
            ],
            options={
                'verbose_name': 'Лента услуг',
                'verbose_name_plural': 'Ленты услуг',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SingleServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('category', models.CharField(choices=[('consulting', 'Консультации'), ('development', 'Разработка'), ('support', 'Поддержка'), ('training', 'Обучение'), ('1_c', '1С')], default='consulting', max_length=100, verbose_name='Категория')),
                ('headline', models.CharField(default='Заголовок услуги', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='1-3 предложения для анонса и первого экрана', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('text_section', 2), ('feature_list', 9), ('steps', 15), ('image_text', 18), ('faq', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5), ('icon', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Список пунктов'}), 9: ('wagtail.blocks.StructBlock', [[('title', 3), ('items', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок блока', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'required': True}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание этапа', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'label': 'Этапы'}), 15: ('wagtail.blocks.StructBlock', [[('title', 10), ('items', 14)]], {}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')], 'label': 'Позиция изображения'}), 18: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 1), ('image', 16), ('image_position', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Вопросы и ответы', 'label': 'Заголовок блока', 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'required': True}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Ответ'}), 22: ('wagtail.blocks.StructBlock', [[('question', 20), ('answer', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Вопросы'}), 24: ('wagtail.blocks.StructBlock', [[('title', 19), ('items', 23)]], {})}, verbose_name='Содержимое страницы')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
            bases=('wagtailcore.page',),
        ),
    ]
