# Generated by Django 6.0.4 on 2026-05-19 09:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleservicepage',
            name='content',
            field=wagtail.fields.StreamField([('text_section', 2), ('simple_list', 7), ('features', 14), ('steps', 20), ('image_text', 23), ('faq', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Текст пункта', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('text', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Пункты'}), 7: ('wagtail.blocks.StructBlock', [[('title', 3), ('items', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание', 'required': False}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10), ('icon', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Список пунктов'}), 14: ('wagtail.blocks.StructBlock', [[('title', 8), ('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок блока', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание этапа', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 16), ('text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Этапы'}), 20: ('wagtail.blocks.StructBlock', [[('title', 15), ('items', 19)]], {}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')], 'label': 'Позиция изображения'}), 23: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 1), ('image', 21), ('image_position', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'Вопросы и ответы', 'label': 'Заголовок блока', 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'required': True}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Ответ'}), 27: ('wagtail.blocks.StructBlock', [[('question', 25), ('answer', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {'label': 'Вопросы'}), 29: ('wagtail.blocks.StructBlock', [[('title', 24), ('items', 28)]], {})}, verbose_name='Содержимое страницы'),
        ),
    ]
