# Generated by Django 6.0.4 on 2026-05-22 05:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_singleservicepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleservicepage',
            name='content',
            field=wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('simple_list', 9), ('features', 16), ('steps', 22), ('image_text', 25), ('faq', 31)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Текст пункта', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Пункты'}), 9: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание', 'required': False}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12), ('icon', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Список пунктов'}), 16: ('wagtail.blocks.StructBlock', [[('title', 10), ('items', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок блока', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'required': True}), 19: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание этапа', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 18), ('text', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'label': 'Этапы'}), 22: ('wagtail.blocks.StructBlock', [[('title', 17), ('items', 21)]], {}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')], 'label': 'Позиция изображения'}), 25: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 1), ('image', 23), ('image_position', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Вопросы и ответы', 'label': 'Заголовок блока', 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'required': True}), 28: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Ответ'}), 29: ('wagtail.blocks.StructBlock', [[('question', 27), ('answer', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'label': 'Вопросы'}), 31: ('wagtail.blocks.StructBlock', [[('title', 26), ('items', 30)]], {})}, verbose_name='Содержимое страницы'),
        ),
    ]
