# Generated by Django 6.0.4 on 2026-05-22 06:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_singleservicepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.SlugField(max_length=100, unique=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='singleservicepage',
            name='content',
            field=wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('features', 11), ('image_text', 14), ('faq', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список пунктов'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Слева'), ('right', 'Справа')], 'label': 'Позиция изображения'}), 14: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 1), ('image', 12), ('image_position', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': 'Вопросы и ответы', 'label': 'Заголовок блока', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Вопрос', 'required': True}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Ответ'}), 18: ('wagtail.blocks.StructBlock', [[('question', 16), ('answer', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Вопросы'}), 20: ('wagtail.blocks.StructBlock', [[('title', 15), ('items', 19)]], {})}, verbose_name='Содержимое страницы'),
        ),
        migrations.RemoveField(
            model_name='singleservicepage',
            name='category',
        ),
        migrations.AddField(
            model_name='singleservicepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Категория'),
        ),
    ]
