# Generated by Django 6.0.4 on 2026-05-11 11:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главные страницы'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='achievements',
            field=wagtail.fields.StreamField([('achievement', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Выберите изображение для иконки (рекомендуемый размер: 50x50px)', 'label': 'Иконка', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'label': 'Числовое значение'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '+', 'label': "Суффикс (например, '+' или '%')", 'max_length': 10}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Краткое название', 'max_length': 100}), 4: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'label': 'Описание достижения'}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('value', 1), ('suffix', 2), ('label', 3), ('description', 4)]], {})}, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='global_presence',
            field=wagtail.fields.StreamField([('presence', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Глобальное присутствие', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'superscript'], 'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: квадратное или 1x1', 'label': 'Изображение для локации', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}, verbose_name='Глобальное присутствие'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 8)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': True}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('url', 3), ('is_secondary', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Кнопки', 'max_num': 2, 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Большое изображение', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('buttons', 6), ('image', 7)]], {})}, verbose_name='Hero секция'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners',
            field=wagtail.fields.StreamField([('partner', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок секции', 'required': True}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 54x16px', 'label': 'Логотип партнёра', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка на партнёра', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('logo', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Логотипы партнёров', 'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subheadline', 1), ('logos', 5)]], {})}, verbose_name='Секция партнёрств'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='work',
            field=wagtail.fields.StreamField([('work_with', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'С кем мы работаем', 'label': 'Заголовок'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Название'}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание'}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 3), ('text', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Карточки', 'min_num': 1}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('intro', 1), ('cards', 6)]], {})}, verbose_name='Секция с кем мы работаем'),
        ),
    ]
