# Generated by Django 6.0.4 on 2026-05-13 10:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_features',
            field=wagtail.fields.StreamField([('feature', 5)], block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок свойства', 'max_length': 50, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Короткое описание', 'max_length': 200, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст ссылки', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link_text', 2), ('page', 3), ('external_url', 4)]], {})}, default=list, verbose_name='Карточки под hero'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 8)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': True}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('url', 3), ('is_secondary', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Кнопки', 'max_num': 2, 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Большое изображение', 'required': True}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('buttons', 6), ('image', 7)]], {})}, verbose_name='Hero секция'),
        ),
    ]
