# Generated by Django 6.0.4 on 2026-06-01 10:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_features_alter_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='achievements',
            field=wagtail.fields.StreamField([('achievement', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Выберите изображение для иконки (рекомендуемый размер: 50x50px)', 'label': 'Иконка', 'required': False}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'label': 'Числовое значение'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '+', 'label': "Суффикс (например, '+' или '%')", 'max_length': 10}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Краткое название', 'max_length': 100}), 4: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'label': 'Описание достижения', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('icon', 0), ('value', 1), ('suffix', 2), ('label', 3), ('description', 4)]], {})}, verbose_name='Достижения'),
        ),
    ]
