# Generated by Django 6.0.4 on 2026-06-10 07:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def create_work_stage_indexes(apps, schema_editor):
    from home.models import HomePage, WorkStageIndexPage

    for home_page in HomePage.objects.only("pk", "path", "depth", "numchild"):
        if WorkStageIndexPage.objects.child_of(home_page).exists():
            continue

        home_page.add_child(
            instance=WorkStageIndexPage(
                title="Этапы работы",
                slug="work-stages",
                show_in_menus=False,
            )
        )


def delete_empty_work_stage_indexes(apps, schema_editor):
    from home.models import HomePage, WorkStageIndexPage

    for home_page in HomePage.objects.only("pk", "path", "depth", "numchild"):
        for stage_index in WorkStageIndexPage.objects.child_of(home_page):
            if not stage_index.get_children().exists():
                stage_index.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_herofeatureindexpage_alter_homepage_hero_features'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStageIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Раздел этапов работы',
                'verbose_name_plural': 'Разделы этапов работы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkStagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название страницы.', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='Вводный текст для первого экрана.', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('features', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список пунктов'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {})}, verbose_name='Содержимое страницы')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Описание этапа работы',
                'verbose_name_plural': 'Описания этапов работы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RunPython(
            create_work_stage_indexes,
            delete_empty_work_stage_indexes,
        ),
    ]
