# Generated by Django 6.0.4 on 2026-06-10 07:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_workstageindexpage_workstagepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='work_stages',
            field=wagtail.fields.StreamField([('work_stages', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'max_length': 120}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Описание этапа'}), 4: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница этапа', 'page_type': ['home.WorkStagePage'], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('page', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Этапы', 'min_num': 1}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('intro', 1), ('stages', 6)]], {})}, verbose_name='Этапы работы'),
        ),
    ]
