# Generated by Django 6.0.4 on 2026-06-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0004_move_indicators_and_work_stages'),
        ('home', '0009_homepage_work_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='achievements',
        ),
    ]
