# Generated by Django 6.0.4 on 2026-06-15 07:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_features',
            field=wagtail.fields.StreamField([('feature', 4)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок свойства', 'max_length': 50, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Короткое описание', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'page_type': ['home.HeroFeaturePage'], 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2), ('page', 3)]], {})}, default=list, verbose_name='Карточки под hero'),
        ),
    ]
