# Generated by Django 6.0.4 on 2026-07-21 07:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_herofeaturepage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='directions',
            field=wagtail.fields.StreamField([('directions', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'max_length': 300, 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Категория', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 1), ('image', 5)]], {'label': 'Главная карточка'}), 7: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 1), ('image', 5)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Дополнительные карточки', 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('main_card', 6), ('cards', 8)]], {})}, verbose_name='Направления аудита'),
        ),
    ]
