# Generated by Django 6.0.4 on 2026-07-22 07:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='service_1c_actions',
            field=wagtail.fields.StreamField([('actions', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'max_length': 300, 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Категория', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст ссылки', 'max_length': 80, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 1), ('image', 5), ('link_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Карточки подключения', 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cards', 8)]], {})}, verbose_name='Действия с сервисами 1С'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='directions',
            field=wagtail.fields.StreamField([('directions', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'max_length': 300, 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Категория', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст ссылки', 'max_length': 80, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 1), ('image', 5), ('link_text', 6)]], {'label': 'Главная карточка'}), 8: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 1), ('image', 5), ('link_text', 6)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Дополнительные карточки', 'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('main_card', 7), ('cards', 9)]], {})}, verbose_name='Направления аудита'),
        ),
    ]
