# Generated by Django 6.0.4 on 2026-07-24 12:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_service_1c_actions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='work',
            new_name='work_with',
        ),
        migrations.AddField(
            model_name='homepage',
            name='products_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Текст отображается только в секции решений.', verbose_name='Дополнительный текст секции решений'),
        ),
    ]
