# Generated by Django 6.0.4 on 2026-08-27 06:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_work_homepage_work_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 17)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': True}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('url', 3), ('is_secondary', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Кнопки', 'max_num': 2, 'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Финансы или Проекты', 'label': 'Короткая подпись', 'max_length': 24, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'max_length': 18}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 7), ('title', 8), ('icon', 9), ('page', 10)]], {'label': 'Центральный узел'}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 7), ('title', 8), ('icon', 9), ('page', 10)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Добавьте от 4 до 6 узлов. Порядок идет сверху по часовой стрелке.', 'label': 'Внешние узлы', 'max_num': 6, 'min_num': 4}), 14: ('wagtail.blocks.StructBlock', [[('center', 11), ('nodes', 13)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('cloud', 14)]], {'label': 'Интерактивное облако', 'max_num': 1, 'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Показывается, пока интерактивное облако не заполнено.', 'label': 'Резервное изображение', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('buttons', 6), ('interactive_cloud', 15), ('image', 16)]], {})}, verbose_name='Hero секция'),
        ),
    ]
