# Generated by Django 6.0.4 on 2026-08-27 08:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='directions',
            field=wagtail.fields.StreamField([('directions', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'max_length': 300, 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Категория', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Описание', 'max_length': 300, 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст ссылки', 'max_length': 80, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 5), ('image', 6), ('link_text', 7)]], {'label': 'Главная карточка'}), 9: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 5), ('image', 6), ('link_text', 7)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Дополнительные карточки', 'min_num': 1}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('main_card', 8), ('cards', 10)]], {})}, verbose_name='Направления аудита'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_1c_actions',
            field=wagtail.fields.StreamField([('actions', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'max_length': 300, 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Категория', 'max_length': 80, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'max_length': 150, 'required': True}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Описание', 'max_length': 300, 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Подробнее', 'label': 'Текст ссылки', 'max_length': 80, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('page', 2), ('category', 3), ('title', 4), ('description', 5), ('image', 6), ('link_text', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'label': 'Карточки подключения', 'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('cards', 9)]], {})}, verbose_name='Действия с сервисами 1С'),
        ),
    ]
