# Generated by Django 6.0.4 on 2026-09-10 10:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_directions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Финансы или Проекты', 'label': 'Короткая подпись', 'max_length': 50, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': True}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4), ('is_secondary', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Кнопки', 'max_num': 2, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Финансы или Проекты', 'label': 'Короткая подпись', 'max_length': 24, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'max_length': 18}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 11: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('eyebrow', 8), ('title', 9), ('icon', 10), ('page', 11)]], {'label': 'Центральный узел'}), 13: ('wagtail.blocks.StructBlock', [[('eyebrow', 8), ('title', 9), ('icon', 10), ('page', 11)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'help_text': 'Добавьте от 4 до 6 узлов. Порядок идет сверху по часовой стрелке.', 'label': 'Внешние узлы', 'max_num': 6, 'min_num': 4}), 15: ('wagtail.blocks.StructBlock', [[('center', 12), ('nodes', 14)]], {}), 16: ('wagtail.blocks.StreamBlock', [[('cloud', 15)]], {'label': 'Интерактивное облако', 'max_num': 1, 'required': False}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Показывается, пока интерактивное облако не заполнено.', 'label': 'Резервное изображение', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('text', 2), ('buttons', 7), ('interactive_cloud', 16), ('image', 17)]], {})}, verbose_name='Hero секция'),
        ),
    ]
