# Generated by Django 6.0.4 on 2026-09-25 09:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Партнер 1С', 'label': 'Короткая подпись', 'max_length': 50, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': True}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4), ('is_secondary', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Кнопки', 'max_num': 2, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Главный текст блока', 'max_length': 50, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Доп описание', 'max_length': 50, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Блоки с важными чертами', 'max_num': 3, 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Финансы или Проекты', 'label': 'Короткая подпись', 'max_length': 24, 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'max_length': 18}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 15: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 16: ('wagtail.blocks.StructBlock', [[('eyebrow', 12), ('title', 13), ('icon', 14), ('page', 15)]], {'label': 'Центральный узел'}), 17: ('wagtail.blocks.StructBlock', [[('eyebrow', 12), ('title', 13), ('icon', 14), ('page', 15)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'help_text': 'Добавьте от 4 до 6 узлов. Порядок идет сверху по часовой стрелке.', 'label': 'Внешние узлы', 'max_num': 6, 'min_num': 4}), 19: ('wagtail.blocks.StructBlock', [[('center', 16), ('nodes', 18)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('cloud', 19)]], {'label': 'Интерактивное облако', 'max_num': 1, 'required': False}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Показывается, пока интерактивное облако не заполнено.', 'label': 'Резервное изображение', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('text', 2), ('buttons', 7), ('proporties', 11), ('interactive_cloud', 20), ('image', 21)]], {})}, verbose_name='Hero секция'),
        ),
    ]
