# Generated by Django 6.0.4 on 2026-10-01 07:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('hero', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Партнер 1С', 'label': 'Короткая подпись', 'max_length': 50, 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка', 'required': True}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Вторичная кнопка', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('url', 4), ('is_secondary', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Кнопки', 'max_num': 2, 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Главный текст блока', 'max_length': 50, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Доп описание', 'max_length': 50, 'required': True}), 10: ('wagtail.blocks.StructBlock', [[('text', 8), ('description', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Блоки с важными чертами', 'max_num': 3, 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'max_length': 18}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Решение'), ('service', 'Сервис'), ('data', 'Данные и интеграции'), ('default', 'Прочее')]}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('title', 12), ('category', 13), ('page', 14)]], {'label': 'Центральный узел'}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('category', 13), ('page', 14)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'help_text': 'Добавьте от 4 до 18 узлов.', 'label': 'Внешние узлы', 'max_num': 18, 'min_num': 4}), 18: ('wagtail.blocks.StructBlock', [[('center', 15), ('nodes', 17)]], {}), 19: ('wagtail.blocks.StreamBlock', [[('cloud', 18)]], {'label': 'Интерактивное облако', 'max_num': 1, 'required': False}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Показывается, пока интерактивное облако не заполнено.', 'label': 'Резервное изображение', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('text', 2), ('buttons', 7), ('proporties', 11), ('interactive_cloud', 19), ('image', 20)]], {})}, verbose_name='Hero секция'),
        ),
    ]
