# Generated by Django 6.0.4 on 2026-10-02 09:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='global_presence',
            field=wagtail.fields.StreamField([('presence', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Глобальное присутствие', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'max_length': 300, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link'], 'label': 'Дополнительный контент', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: квадратное или 1x1', 'label': 'Изображение для локации', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('content', 2), ('image', 3)]], {})}, verbose_name='Глобальное присутствие'),
        ),
    ]
