# Generated by Django 6.0.4 on 2026-10-02 12:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_homepage_global_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='work_stages',
            field=wagtail.fields.StreamField([('work_stages', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Как мы работаем', 'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Название этапа', 'max_length': 120}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Описание этапа'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Результат этапа'}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница этапа', 'page_type': ['home.WorkStagePage'], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3), ('result_text', 4), ('page', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Этапы', 'min_num': 1}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('intro', 1), ('stages', 7)]], {})}, verbose_name='Этапы работы'),
        ),
    ]
