# Generated by Django 6.0.4 on 2026-06-10 07:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0002_alter_aboutpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='indicators',
            field=wagtail.fields.StreamField([('indicators', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Наши достижения в цифрах', 'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Выберите изображение для иконки (рекомендуемый размер: 50x50px)', 'label': 'Иконка', 'required': False}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 0, 'label': 'Числовое значение'}), 4: ('wagtail.blocks.CharBlock', (), {'blank': True, 'default': '+', 'label': "Суффикс (например, '+' или '%')", 'max_length': 10}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Краткое название', 'max_length': 100}), 6: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'label': 'Описание достижения', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('icon', 2), ('value', 3), ('suffix', 4), ('label', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Достижения', 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('intro', 1), ('items', 8)]], {})}, verbose_name='Показатели'),
        ),
    ]
