# Generated by Django 6.0.4 on 2026-06-10 07:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_company', '0004_move_indicators_and_work_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=wagtail.fields.StreamField([('features', 6), ('rich_text', 9), ('work_with', 17), ('partners', 24), ('certificates', 32)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 1), ('text', 2), ('icon', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Список пунктов'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('items', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 9: ('wagtail.blocks.StructBlock', [[('title', 7), ('text', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'С кем мы работаем', 'label': 'Заголовок'}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание', 'required': False}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Название'}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Описание'}), 15: ('wagtail.blocks.StructBlock', [[('image', 12), ('title', 13), ('text', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Карточки', 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('title', 10), ('intro', 11), ('cards', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Подзаголовок секции', 'required': True}), 20: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Рекомендуемый размер: 54x16px', 'label': 'Логотип партнёра', 'required': True}), 21: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка на партнёра', 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('logo', 20), ('link', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Логотипы партнёров', 'min_num': 1}), 24: ('wagtail.blocks.StructBlock', [[('headline', 18), ('subheadline', 19), ('logos', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Сертификаты', 'label': 'Заголовок', 'required': False}), 26: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение сертификата', 'required': True}), 27: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'required': False}), 28: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 29: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Файл', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('image', 26), ('title', 27), ('description', 28), ('file', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'label': 'Сертификаты', 'min_num': 1}), 32: ('wagtail.blocks.StructBlock', [[('title', 25), ('intro', 11), ('items', 31)]], {})}, verbose_name='Содержимое страницы'),
        ),
    ]
