# Generated by Django 6.0.4 on 2026-05-12 05:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, default='', help_text='Название сайта, отображаемое рядом с логотипом', max_length=255)),
                ('consultation_button_text', models.CharField(default='Оставить заявку', help_text='Текст кнопки консультации', max_length=255)),
                ('nav_items', wagtail.fields.StreamField([('nav_item', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название пункта меню', 'label': 'Название пункта*', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу для ссылки', 'label': 'Страница', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Укажите внешний URL, если страница не выбрана', 'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Без подменю'), ('simple', 'Простое подменю')], 'help_text': 'Выберите тип подменю', 'label': 'Тип меню*'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название подпункта', 'label': 'Название подпункта*', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('name', 4), ('page', 1), ('external_url', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': "Используется для типа 'Простое подменю'", 'label': 'Элементы подменю', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('external_url', 2), ('menu_type', 3), ('simple_dropdown_items', 6)]], {'icon': 'list-ul', 'label': 'Пункт меню'})}, default=list)),
                ('logo', models.ForeignKey(blank=True, help_text='Логотип сайта (рекомендуемый размер: 40x40px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Хедер',
                'verbose_name_plural': 'Хедер',
            },
        ),
    ]
