# Generated by Django 6.0.4 on 2026-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Краткое описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Обсудим ваш проект на базе 1С', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Режим работы')),
                ('form_title', models.CharField(default='Получить консультацию', max_length=255, verbose_name='Заголовок формы')),
                ('submit_button_text', models.CharField(default='Отправить заявку', max_length=100, verbose_name='Текст кнопки')),
                ('form_note', models.CharField(default='Ответим и предложим следующий шаг по проекту.', max_length=255, verbose_name='Текст рядом с кнопкой')),
                ('privacy_policy_text', models.TextField(default="Нажимая кнопку, вы соглашаетесь с <a href='/privacy-policy/'>политикой обработки персональных данных</a>", verbose_name='Текст политики конфиденциальности')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
    ]
