# Generated by Django 6.0.4 on 2026-05-13 08:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_consultationrequest_contactsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_columns', wagtail.fields.StreamField([('column', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок колонки', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('url', 2), ('page', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Ссылки'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 5)]], {'label': 'Колонка ссылок'})})),
                ('social_links', wagtail.fields.StreamField([('social', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Наши социальные сети', 'label': 'Заголовок колонки', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'max_length': 50}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('url', 2), ('icon', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Соцсеть'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 5)]], {'label': 'Соцсети'})})),
                ('bottom_links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 100}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1), ('page', 2)]], {'label': 'Нижняя ссылка'})})),
                ('footer_button', models.CharField(default='Связаться с нами', max_length=50, verbose_name='Текст кнопки')),
                ('footer_button_href', models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки (например, #contact или /contact)')),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
    ]
