# Generated by Django 6.0.4 on 2026-05-21 08:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_footersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='privacy_policy_text',
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='bottom_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Текст', 'max_length': 100}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 1), ('page', 2)]], {'label': 'Нижняя ссылка'})}, verbose_name='Нижние ссылки'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='link_columns',
            field=wagtail.fields.StreamField([('column', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок колонки', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Текст ссылки', 'max_length': 100}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('url', 2), ('page', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Ссылки'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 5)]], {'label': 'Колонка ссылок'})}, verbose_name='Колонки ссылок'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='social_links',
            field=wagtail.fields.StreamField([('social', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Наши социальные сети', 'label': 'Заголовок колонки', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Название', 'max_length': 50}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'Ссылка'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('text', 1), ('url', 2), ('icon', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Соцсеть'}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('links', 5)]], {'label': 'Соцсети'})}, verbose_name='Соцсети'),
        ),
    ]
