# Generated by Django 6.0.4 on 2026-06-10 08:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_contactsettings_privacy_policy_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='nav_items',
            field=wagtail.fields.StreamField([('nav_item', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название пункта меню', 'label': 'Название пункта*', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу для ссылки', 'label': 'Страница', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Укажите внешний URL, если страница не выбрана', 'label': 'Внешняя ссылка', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Без подменю'), ('simple', 'Простое подменю'), ('mega', 'Мегаменю')], 'help_text': 'Выберите тип подменю', 'label': 'Тип меню*'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название подпункта', 'label': 'Название подпункта*', 'max_length': 255, 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('name', 4), ('page', 1), ('external_url', 2)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': "Используется для типа 'Простое подменю'", 'label': 'Элементы подменю', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Название карточки', 'max_length': 255, 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 7), ('description', 8), ('page', 9), ('external_url', 10)]], {'icon': 'doc-full', 'label': 'Карточка мегаменю'}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': "Используется для типа 'Мегаменю'", 'label': 'Карточки мегаменю', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('name', 0), ('page', 1), ('external_url', 2), ('menu_type', 3), ('simple_dropdown_items', 6), ('mega_menu_items', 12)]], {'icon': 'list-ul', 'label': 'Пункт меню'})}, default=list),
        ),
    ]
