# Generated by Django 6.0.4 on 2026-07-08 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirm_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
