# Generated by Django 6.0.4 on 2026-09-01 09:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_subscriber_confirm_token_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='nav_items',
            field=wagtail.fields.StreamField([('nav_item', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название пункта меню', 'label': 'Название пункта*', 'max_length': 255, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу для ссылки', 'label': 'Страница', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Укажите внешний URL, если страница не выбрана', 'label': 'Внешняя ссылка', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'Без подменю'), ('simple', 'Простое подменю'), ('mega', 'Широкое подменю')], 'help_text': 'Выберите тип подменю', 'label': 'Тип меню*'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название подпункта', 'label': 'Название подпункта*', 'max_length': 255, 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('name', 5), ('page', 2), ('external_url', 3)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': "Используется для типа 'Простое подменю'", 'label': 'Элементы подменю', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Название карточки', 'max_length': 255, 'required': True}), 9: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Страница', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 8), ('description', 1), ('page', 9), ('external_url', 10)]], {'icon': 'doc-full', 'label': 'Карточка расширенного подменю'}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': "Используется для типа 'Широкое подменю'", 'label': 'Карточки широкого подменю', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('name', 0), ('intro', 1), ('page', 2), ('external_url', 3), ('menu_type', 4), ('simple_dropdown_items', 7), ('mega_menu_items', 12)]], {'icon': 'list-ul', 'label': 'Пункт меню'})}, default=list),
        ),
    ]
