# Generated by Django 6.0.4 on 2026-05-22 07:25

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service1CIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(default='Сервисы 1С', max_length=255, verbose_name='Заголовок')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
                ('items_per_page', models.PositiveIntegerField(default=9, verbose_name='Сервисов на странице')),
            ],
            options={
                'verbose_name': 'Лента сервисов 1С',
                'verbose_name_plural': 'Ленты сервисов 1С',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SingleService1CPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('headline', models.CharField(default='Заголовок продукта 1C', max_length=255, verbose_name='Заголовок')),
                ('intro', models.TextField(blank=True, help_text='1-3 предложения для анонса и первого экрана', verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('features', 11), ('cta', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': 'Описание', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список пунктов'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Оставить заявку на подключение сервиса', 'label': 'Заголовок', 'required': True}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Отправить', 'label': 'Текст кнопки', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'default': '#contacts', 'help_text': 'Например: #contacts или /contacts/', 'label': 'Ссылка кнопки', 'max_length': 200, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('text', 13), ('button_text', 14), ('button_url', 15)]], {})}, verbose_name='Содержимое страницы')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сервис 1С',
                'verbose_name_plural': 'Сервисы 1С',
            },
            bases=('wagtailcore.page',),
        ),
    ]
