# Generated by Django 6.0.4 on 2026-06-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_1C', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service1cindexpage',
            options={'verbose_name': 'Лента решений 1С', 'verbose_name_plural': 'Ленты решений 1С'},
        ),
        migrations.AlterModelOptions(
            name='singleservice1cpage',
            options={'verbose_name': 'Решение 1С', 'verbose_name_plural': 'Решения 1С'},
        ),
    ]
