# Generated by Django 6.0.4 on 2026-06-23 11:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_1C', '0002_alter_service1cindexpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service1CCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('value', models.SlugField(max_length=100, unique=True, verbose_name='Значение для URL')),
            ],
            options={
                'verbose_name': 'Категория 1С',
                'verbose_name_plural': 'Категории 1С',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='singleservice1cpage',
            name='content',
            field=wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('features', 11), ('cta', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Описание', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список пунктов'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Оставить заявку на подключение сервиса', 'label': 'Заголовок', 'required': True}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Отправить', 'label': 'Текст кнопки', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'default': '#contacts', 'help_text': 'Например: #contacts или /contacts/', 'label': 'Ссылка кнопки', 'max_length': 200, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('text', 13), ('button_text', 14), ('button_url', 15)]], {})}, verbose_name='Содержимое страницы'),
        ),
        migrations.AddField(
            model_name='singleservice1cpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_1c', to='services_1C.service1ccategory', verbose_name='Категория'),
        ),
    ]
