# Generated by Django 6.0.4 on 2026-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_1C', '0003_service1ccategory_alter_singleservice1cpage_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service1ccategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория сервиса 1С', 'verbose_name_plural': 'Категории сервисов 1С'},
        ),
        migrations.AlterModelOptions(
            name='service1cindexpage',
            options={'verbose_name': 'Лента сервисов 1С', 'verbose_name_plural': 'Ленты сервисов 1С'},
        ),
        migrations.AlterModelOptions(
            name='singleservice1cpage',
            options={'verbose_name': 'Сервис 1С', 'verbose_name_plural': 'Сервисы 1С'},
        ),
        migrations.AlterField(
            model_name='singleservice1cpage',
            name='headline',
            field=models.CharField(default='Заголовок сервиса 1C', max_length=255, verbose_name='Заголовок'),
        ),
    ]
