# Generated by Django 6.0.4 on 2026-07-08 07:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_1C', '0004_alter_service1ccategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleservice1cpage',
            name='content',
            field=wagtail.fields.StreamField([('text_section', 2), ('table', 4), ('features', 11), ('cta', 16), ('rates', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Текст'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица'}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('table', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Преимущества', 'label': 'Заголовок блока', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote'], 'label': 'Описание', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Иконка', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('icon', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Список пунктов'}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('items', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Оставить заявку на подключение сервиса', 'label': 'Заголовок', 'required': True}), 13: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Отправить', 'label': 'Текст кнопки', 'max_length': 100, 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'default': '#contacts', 'help_text': 'Например: #contacts или /contacts/', 'label': 'Ссылка кнопки', 'max_length': 200, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 12), ('text', 13), ('button_text', 14), ('button_url', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Период тарифа', 'required': False}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Цена продления', 'label': 'Заголовок цены', 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Цена тарифа', 'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'label': 'Текст кнопки', 'max_length': 50, 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'default': '#contacts', 'help_text': 'Например: #contacts, /contacts/, https://example.com', 'label': 'Ссылка или якорь', 'max_length': 255, 'required': True}), 22: ('wagtail.blocks.StructBlock', [[('text', 20), ('url', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Рекомендованная цена', 'label': 'Заголовок рекомендованной цены', 'required': False}), 24: ('wagtail.blocks.TextBlock', (), {'label': 'Рекомендованная цена', 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('title', 6), ('period', 17), ('price_title', 18), ('price', 19), ('button', 22), ('rec_price_title', 23), ('rec_price', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'label': 'Список тарифов'}), 27: ('wagtail.blocks.StructBlock', [[('title', 0), ('rates', 26)]], {})}, verbose_name='Содержимое страницы'),
        ),
    ]
