# Generated by Django 6.0.4 on 2026-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_singleproductpage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория решения', 'verbose_name_plural': 'Категории решений'},
        ),
        migrations.AlterModelOptions(
            name='productindexpage',
            options={'verbose_name': 'Лента решений', 'verbose_name_plural': 'Ленты решений'},
        ),
        migrations.AlterModelOptions(
            name='singleproductpage',
            options={'verbose_name': 'Решение', 'verbose_name_plural': 'Решения'},
        ),
        migrations.AlterField(
            model_name='productindexpage',
            name='headline',
            field=models.CharField(default='Решения', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='productindexpage',
            name='items_per_page',
            field=models.PositiveIntegerField(default=9, verbose_name='Решений на странице'),
        ),
        migrations.AlterField(
            model_name='singleproductpage',
            name='headline',
            field=models.CharField(default='Заголовок решения', max_length=255, verbose_name='Заголовок'),
        ),
    ]
